version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env.local
    ports:
      - "3000:3000"
    # Overrides default command so things don't shut down after the process ends
    # Keep the container alive
    tty: true
